### PR TITLE
RFC: redesign of metamodel for map key and map value types

### PR DESCRIPTION
**Pull request by Jonathan-Casey**
Drafting the redesign of the metamodel for a MapDeclarations Key and Value Types.

```
abstract concept MapKeyType {
  o Decorator[] decorators optional
  o Range location optional
}

abstract concept MapValueType {
  o Decorator[] decorators optional
  o Range location optional
}

concept MapDeclaration extends Declaration {
  o MapKeyType key
  o MapValueType value
}

concept StringMapKeyType extends MapKeyType {}
concept DateTimeMapKeyType extends MapKeyType {}

concept ObjectMapKeyType extends MapKeyType {
  o TypeIdentifier type
}

concept BooleanMapValueType extends MapValueType {}
concept DateTimeMapValueType extends MapValueType {}
concept StringMapValueType extends MapValueType {}
concept IntegerMapValueType extends MapValueType {}
concept LongMapValueType extends MapValueType {}
concept DoubleMapValueType extends MapValueType {}

concept ObjectMapValueType extends MapValueType {
  o TypeIdentifier type
}

concept RelationshipMapValueType extends MapValueType {
  o TypeIdentifier type
}
```

### CODE REVIEW

**Comment by Jonathan-Casey** [comment]
@mttrbrts thoughts on the rename of` AggregateValueType `-> `MapValueType` ?

**Comment by DS-AdamMilazzo** [comment]
A few brief comments:

* I like the rename to MapValueType.
* It seems like you could also support references/relationships as keys, since they're strings.
* It seems like "ObjectMapKeyType" is a bit of a misnomer, since the key is not an object, but I realize that it aligns with ObjectProperty (which is unfortunately named now that it's also used for user-defined scalars, which aren't objects). "User" or "UserDefined" seems more accurate than "Object", except that it would be inconsistent with the existing ObjectProperty, which is probably hard to change at this point.
* This pattern of using Boolean, DateTime, Integer, etc. prefixes matches the rest of the metamodel, but it's a bit ugly. It might be nice if a TypeIdentifier could refer to a built-in type as well as a user-defined type. One way of doing that is to use the magic `concerto` model that you have (where the special "Concept" type is defined). You could use `concerto@1.0.0.Boolean`, `concerto@1.0.0.DateTime`, etc. to refer to built-in types. I realize that it'd be a big change to do that across the metamodel (because it would obsolete most of the \*Property and \*Scalar concepts), and only doing it here for the map support would be inconsistent with the rest of the metamodel. Anyway, it's just an idea for the future.

**Comment by mttrbrts** [comment]
> It seems like "ObjectMapKeyType" is a bit of a misnomer, since the key is not an object, but I realize that it aligns with ObjectProperty (which is unfortunately named now that it's also used for user-defined scalars, which aren't objects). 

I agree, our goal is internal consistency at this stage.

> This pattern of using Boolean, DateTime, Integer, etc. prefixes matches the rest of the metamodel, but it's a bit ugly. It might be nice if a TypeIdentifier could refer to a built-in type as well as a user-defined type. One way of doing that is to use the magic concerto model that you have (where the special "Concept" type is defined). You could use concerto@1.0.0.Boolean, concerto@1.0.0.DateTime, etc. to refer to built-in types. I realize that it'd be a big change to do that across the metamodel (because it would obsolete most of the *Property and *Scalar concepts), and only doing it here for the map support would be inconsistent with the rest of the metamodel. Anyway, it's just an idea for the future.

I'm supportive of this direction, @DS-AdamMilazzo. @Jonathan-Casey and I discussed it yesterday, but it's very invasive. Let's keep it on the table for a future major upgrade.

**Review by mttrbrts — APPROVED** [review]

**Review by dselman — APPROVED** [review]

**Comment by DS-AdamMilazzo** [comment]
While we're revisiting the design, I'll note that you could also support integers and other non-string, scalar types as keys. They'd simply be converted to/from string. E.g.
```
map M {
  o Integer
  o Foo
}
```
could look like:
```
{
  "1": { ... },
  "2": { ... }
}
```
This is how C# data types like Dictionary\<int, Foo\> are normally serialized to/from JSON, for example.

The wrinkle, however, is the lack of a 1:1 mapping from int to string. "1" and "1.0" and "0.1e1" are all ways to represent the integer 1 in JSON, so presumably a map value like the following should fail validation for duplicate keys:
```
{
  "1": { ... },
  "1.0": { ... }
}
```
Serialization is easy, though.

**Pull request merged**
